l1:
  - gümrük
  - gumruk
  - ithalat
  - ithalatta
  - ihracat
  - dış ticaret
  - dis ticaret
  - gtip
  - g.t.i.p
  - tarife
  - kontenjan
  - kota
  - damping
  - haksız rekabet
  - ürün güvenliği
  - urun guvenligi
  - menşe
  - mense
  - serbest bölge
  - geçici ithalat
  - tareks
l2:
  - ötv
  - kdv
  - döviz
  - kambiyo
  - destek
  - teşvik
  - yaptırım
  - akaryakıt
  - tarım kontrol
  - resmi kontrol
  - malvarlığının dondurulması
  - birleşmiş milletler güvenlik konseyi
l3:
  - üniversitesi uygulama ve araştırma merkezi
  - atama hakkında karar
  - acele kamulaştırılması
  - anayasa mahkemesinin
  - başvuru numaralı karar
  - ilan
  - ilân
